### ISSUE TITLE
cannot  select nahida 

### ISSUE THREAD

**Issue by RC4-sys** [Cheshire1922/NahidaGC#1]
excuse~ I cannot select nahida if I give her by /give 1073 .But I can find nahida in your screenshot.

**Comment by RC4-sys** [comment]
![image](https://user-images.githubusercontent.com/66230337/195531784-2164c97e-a1a0-4bb7-a893-1210a5aa3fb9.png)

**Comment by Cheshire1922** [comment]
uhhh.. nahida works perfect for me
try /give all maybe? or restart your game

**Comment by RC4-sys** [comment]
> 
I have a try,but not works.I think it may be the problem of local resources of the game
![image](https://user-images.githubusercontent.com/66230337/195534965-5c4b8cda-0ee3-40b7-88bd-ccb10a7a10c6.png)

**Comment by Cheshire1922** [comment]
You were using 3.1, this server is for 3.1.5(3.2 beta)
